apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: component-github-iup62pohftymv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: component-github-iup62pohftymv
    app.kubernetes.io/part-of: application-github-wma0zjwzf7e3s
  name: component-github-iup62pohftymv
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: go-app
    app.kubernetes.io/instance: component-github-iup62pohftymv
status:
  loadBalancer: {}
