apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: component-github-cbu75768uuocm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: component-github-cbu75768uuocm
    app.kubernetes.io/part-of: application-github-wma0zjwzf7e3s
  name: component-github-cbu75768uuocm
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: component-github-cbu75768uuocm
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: component-github-cbu75768uuocm
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-spi-tenant/remotesecret/remotesecret-operator@sha256:10cde34c19be468138cf883274c9c7c81270403d8d7b1b0dc62ca8798a151c7a
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 15m
            memory: 30Mi
          requests:
            cpu: 10m
            memory: 25Mi
status: {}
